package userInterface.finalGUI.panels;

import userInterface.finalGUI.TradeNetGUIConstants;

import javax.swing.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 * Controller for generating the views for the panels as well as
 * handling any display of errors generated from the sub panels.
 */
public class GUIController extends JFrame implements PropertyChangeListener{

    /**
     * Generate a new Controller.
     * Should only be called one from the {@link userInterface.finalGUI.TradeNetGUI}.
     */
    public GUIController(){
        super();
        setTitle(TradeNetGUIConstants.TITLE);
        setSize(TradeNetGUIConstants.DEFAULT_GUI_WIDTH, TradeNetGUIConstants.DEFAULT_GUI_HEIGHT);
        setResizable(false);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        buildFrame();
    }

    /**
     * Construct the parent frame that houses all sub class panels.
     */
    private void buildFrame(){

    }

    /**
     * Handle each event given to this {@link GUIController},
     * only handle events that are generated by panels,
     * and only events that are of type {@link CustomChangeEvent}.
     */
    @Override
    public void propertyChange(PropertyChangeEvent evt) {

    }
}
